In [1]:
import pandas as pd

In [18]:
df = pd.read_csv("IRIS.csv")
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [9]:
#display first 10 rows
# df.head(10)

#shape and data types
# print(df.shape, type(df))

#summary ---> mean, min, max, dev
# print(df.describe())

In [34]:
# ''' Select only those rows where: B. •
# petal_length > 4.5 •
# species = "Iris-virginica"'''

# print(df.query('petal_length > 4.5 and species == "Iris-virginica"'))

In [36]:
'''
ompute: C. species •
Average sepal_length •
Maximum petal_width •
Standard deviation of sepal_width
'''


# df.groupby("species")["sepal_length"].mean()

# df.groupby("species")["petal_width"].max()

# df.groupby("species")["sepal_width"].std()

species
Iris-setosa        0.381024
Iris-versicolor    0.313798
Iris-virginica     0.322497
Name: sepal_width, dtype: float64

In [41]:
'''
D. "petal_ratio" = petal_length / petal_width •
For each species, find the average petal_ratio.
'''

# df["petal_ratio"] = (df["petal_length"]) / (df["petal_width"])

# df.groupby("species") ["petal_ratio"].mean()

'\nD. "petal_ratio" = petal_length / petal_width •\nFor each species, find the average petal_ratio.\n'

In [45]:
df = pd.read_csv("Titanic-Dataset.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [48]:
# . Name, Sex, Age, Fare, Survived

# df[["Name", "Sex", "Age", "Fare", "Survived"]]

In [53]:
'''
Select passengers who: B. •
Are female •
Fare > 30
'''

# df.query('Sex == "female" & Fare > 30')

'\nSelect passengers who: B. •\nAre female •\nFare > 30\n'

In [60]:
'''
Group by Pclass  and compute
Survival rate
Average Fare 
Average Age
'''

# survival_rate = df.groupby("Pclass") ["Survived"].mean() * 100
# print(survival_rate)

# avg_fare = df.groupby("Pclass") ["Fare"].mean()
# print(avg_fare)

# avg_age = df.groupby("Pclass") ["Age"].mean()
# print(avg_age)

'\nGroup by Pclass  and compute\nSurvival rate\nAverage Fare \nAverage Age\n'